/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
static yyconst short int yy_accept[269] =
    {   0,
       13,   13,   20,   18,   17,   17,   18,   18,   18,   18,
       18,   18,    8,    5,    5,    5,   13,   13,    8,    5,
        8,   15,   15,   15,   15,   15,   15,   15,   15,   18,
        0,    6,    0,    3,    0,    0,    0,   16,    6,    0,
        4,    0,    0,    0,   13,   13,    0,    1,   14,   13,
        9,   10,   11,    5,    6,   15,   15,   15,   15,   15,
       15,   15,    7,   15,   15,   15,    0,    0,    0,   16,
        0,    0,    0,    0,    1,   14,    9,    9,   10,   10,
       11,   11,   11,   15,   15,   15,   15,    7,   15,   15,
       15,   15,    0,   12,    0,   12,    0,    0,   12,   12,

        2,    9,   10,   11,   11,   15,   15,   15,   12,    7,
       15,   15,   15,   12,   12,    0,   12,   12,   11,   15,
       15,   15,   12,   12,   15,   15,    7,    0,   11,   15,
       15,   15,   12,   12,    7,    0,   15,   15,   15,   12,
       12,    7,   15,   15,   15,   12,   12,   15,   15,   15,
       12,   12,   15,   15,   15,   12,   12,   15,   15,   15,
       12,   12,   15,   15,   15,   12,   12,   15,   15,   15,
       12,   12,   15,   15,   15,   12,   12,   15,   15,   15,
       12,   12,   15,   15,   15,   12,   12,   15,   15,   15,
       12,   12,   15,   15,   15,   12,   12,   15,   15,   15,

       12,   12,   15,   15,   15,   12,   12,   15,   15,   15,
       12,   12,   15,   15,   15,   12,   12,   15,   15,   15,
       12,   12,   15,   15,   15,   12,   12,   15,   15,   15,
       12,   12,   15,   15,   15,   12,   12,   15,   15,   15,
       12,   12,   15,   15,   15,   12,   12,   15,   15,   15,
       12,   12,   15,   15,   15,   12,   12,   15,   15,   15,
       12,   12,   15,   15,   15,   12,   12,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    1,    8,    9,   10,
       10,   11,   12,   10,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   10,   10,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   24,   23,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       10,   26,   10,   27,   28,    1,   29,   30,   31,   32,

       33,   34,   25,   35,   36,   25,   25,   37,   25,   38,
       39,   25,   25,   40,   41,   42,   43,   25,   44,   45,
       25,   25,   10,   46,   10,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[47] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    4,    4,    4,    4,    1,
        1,    1,    4,    4,    5,    1,    1,    5,    4,    4,
        4,    4,    4,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1
    } ;

static yyconst short int yy_base[309] =
    {   0,
        0,    0,  329,   31,   35, 1174,   39,   54,   45,   49,
       66,   60,   71,   75,   79,   88,   94,  100,  109,  119,
      125,  104,  132,   67,  117,  118,  121,   99,  291,  147,
      152,  304,  153, 1174,  189,  313,  277,    0, 1174,  151,
     1174,  214,  309,  156,  234,  254,  300,    0,  164,  171,
      182,  200,  210, 1174,  288,  258,    0,  279,  269,  261,
      256,  257,    0,  241,  239,  233,  224,  287,  226,    0,
      305,  243,  243,  210,    0,  277,  175,  318,  193,  338,
        0,  358,  235,  377,    0,  267,  199,    0,  202,  201,
      177,  175,  227,  247,  302,  322,  160,  341,  388,  399,

      175,  186,  272,    0,  351,  403,    0,  366,  327,    0,
      144,  138,  128,  412,  421,  102,  425,  436,  445,  449,
        0,  458,  462,  467,   93,   77,    0,   77,    0,  471,
        0,  479,  483,  489,    0,   68,  493,    0,  501,  505,
      511, 1174,  515,    0,  523,  527,  533,  537,    0,  545,
      549,  555,  559,    0,  567,  571,  577,  581,    0,  589,
      593,  599,  603,    0,  611,  615,  621,  625,    0,  633,
      637,  643,  647,    0,  655,  659,  665,  669,    0,  677,
      681,  687,  691,    0,  699,  703,  709,  713,    0,  721,
      725,  731,  735,    0,  743,  747,  753,  757,    0,  765,

      769,  775,  779,    0,  787,  791,  797,  801,    0,  809,
      813,  819,  823,    0,  831,  835,  841,  845,    0,  853,
      857,  863,  867,    0,  875,  879,  885,  889,    0,  897,
      901,  907,  911,    0,  919,  923,  929,  933,    0,  941,
      945,  951,  955,    0,  963,  967,  973,  977,    0,  985,
      989,  995,  999,    0, 1007, 1011, 1017, 1021,    0, 1029,
     1033, 1039, 1043, 1174, 1051, 1055, 1061, 1174, 1080, 1082,
     1087, 1092, 1094, 1096, 1101, 1106, 1109, 1110,   71, 1112,
     1114, 1116, 1118, 1120, 1122, 1124, 1126, 1128, 1130, 1132,
     1134, 1136, 1138, 1140, 1142, 1144, 1146, 1148, 1150, 1152,

     1154, 1156, 1158, 1160, 1162, 1164, 1166, 1168
    } ;

static yyconst short int yy_def[309] =
    {   0,
      268,    1,  268,  268,  268,  268,  268,  269,  268,  270,
      268,  271,  268,  268,  272,  268,  272,  272,  268,  268,
      268,  273,  273,   23,   23,   23,   23,   23,   23,  268,
      268,  268,  269,  268,  269,  269,  268,  274,  268,  271,
      268,  271,  271,  268,  272,  272,  275,  276,  268,  272,
      268,  268,  277,  268,  268,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  268,  269,  268,  274,
      271,  268,  275,  275,  276,  268,  268,  268,  268,  268,
      279,  268,  277,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  268,  268,  269,  269,  268,  271,  271,  268,

      275,  268,  268,  279,  277,  281,  281,  281,  281,  281,
      281,  281,  281,  268,  269,  268,  271,  268,  277,  282,
      282,  282,  282,  282,  282,  282,  282,  268,  119,  283,
      283,  283,  283,  283,  283,  268,  284,  284,  284,  284,
      284,  268,  285,  285,  285,  285,  285,  286,  286,  286,
      286,  286,  287,  287,  287,  287,  287,  288,  288,  288,
      288,  288,  289,  289,  289,  289,  289,  290,  290,  290,
      290,  290,  291,  291,  291,  291,  291,  292,  292,  292,
      292,  292,  293,  293,  293,  293,  293,  294,  294,  294,
      294,  294,  295,  295,  295,  295,  295,  296,  296,  296,

      296,  296,  297,  297,  297,  297,  297,  298,  298,  298,
      298,  298,  299,  299,  299,  299,  299,  300,  300,  300,
      300,  300,  301,  301,  301,  301,  301,  302,  302,  302,
      302,  302,  303,  303,  303,  303,  303,  304,  304,  304,
      304,  304,  305,  305,  305,  305,  305,  306,  306,  306,
      306,  306,  307,  307,  307,  307,  307,  308,  308,  308,
      308,  308,  268,  268,  268,  268,  268,    0,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268
    } ;

static yyconst short int yy_nxt[1221] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   14,   15,   13,   16,   17,   18,   18,   18,   19,
       20,   21,   22,   22,   22,    4,   14,    4,   22,   22,
       23,   24,   25,   26,   22,   27,   22,   22,   22,   28,
       22,   22,   22,   29,   22,   30,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   34,   32,
       31,   31,   31,   31,   31,   31,   31,   31,   41,   35,
       35,   35,   35,   39,  104,   42,   42,   42,   42,   36,
       37,   31,   31,   31,   31,   43,   31,   31,   31,   31,
       31,   31,   31,   31,   45,   46,   46,   46,   47,   59,

      142,   57,   48,   31,   31,   31,   31,   49,  136,   50,
       50,   50,   50,   49,  135,   45,   46,   46,   46,   56,
       56,   56,   56,   51,   31,   31,   31,   31,   54,   39,
      135,   65,   52,   57,   31,   31,   31,   31,   53,   55,
       31,   31,   31,   31,  128,   39,   54,   56,   56,   56,
       56,   57,   57,   60,   63,   57,   62,   34,   64,   41,
      127,   61,   31,   31,   31,   31,   58,   31,   31,   31,
       31,   31,   31,   31,   31,   67,   43,  126,   36,   76,
       76,   76,   76,  125,   67,   74,   50,   50,   50,   50,
      102,  102,   39,   34,   72,   77,  116,   78,   78,   31,

       31,  102,  102,   72,   35,   35,   35,   35,  103,  103,
      103,  113,   68,   79,   36,   80,   80,   80,   31,  112,
       74,   68,   41,   81,  101,   82,   82,   82,   82,   42,
       42,   42,   42,  111,  110,   93,   93,   71,  110,   43,
       94,   94,   94,   94,   94,   94,   71,   49,   81,   50,
       50,   50,   50,   74,   93,   93,   97,   72,   31,  100,
      100,  100,  114,  114,  114,  114,   72,   49,   92,   45,
       46,   46,   46,   84,   84,   84,   84,   72,   93,   93,
       91,   86,   88,  109,  109,  109,   72,  103,  103,  103,
       86,   34,   76,   76,   76,   76,   88,   90,   95,   95,

       67,   89,   88,   96,   96,   96,   34,   87,   39,   67,
       74,  268,   36,   41,   69,  268,   98,   98,   96,   96,
       96,   99,   99,   99,   39,   66,   34,   36,  268,  268,
       43,   77,  268,   78,   78,   31,   31,  115,  115,  115,
      115,   67,  124,  124,  124,  124,  268,   36,  268,   41,
       67,   79,  268,   80,   80,   80,   31,   99,   99,   99,
      268,   67,   93,   93,   81,  268,   43,  119,  119,  119,
       67,   81,  268,   82,   82,   82,   82,   93,   93,  268,
       83,  105,  123,  123,  123,  268,   83,   83,   83,   83,
      105,   83,  106,  106,  106,  106,   41,  268,  268,  268,

      108,  268,  268,  117,  117,  117,  117,  268,  268,  108,
      268,  268,  268,   43,  118,  118,  118,  118,  120,  120,
      120,  120,   67,  268,  268,   34,  122,  114,  114,  114,
      114,   67,  268,   41,  268,  122,  115,  115,  115,  115,
      117,  117,  117,  117,  268,  268,   36,  268,  268,  268,
       43,  118,  118,  118,  118,  268,  268,  268,   81,   67,
      129,  129,  129,  129,  130,  130,  130,  130,   67,   93,
       93,  268,  132,  268,  133,  133,  133,  134,  134,  134,
      134,  132,  134,  134,  134,  134,  137,  137,  137,  137,
       93,   93,  268,  268,  139,  140,  140,  140,  141,  141,

      141,  141,  268,  139,  141,  141,  141,  141,  143,  143,
      143,  143,   93,   93,  268,  268,  145,  146,  146,  146,
      147,  147,  147,  147,  268,  145,  147,  147,  147,  147,
      148,  148,  148,  148,   93,   93,  268,  268,  150,  151,
      151,  151,  152,  152,  152,  152,  268,  150,  152,  152,
      152,  152,  153,  153,  153,  153,   93,   93,  268,  268,
      155,  156,  156,  156,  157,  157,  157,  157,  268,  155,
      157,  157,  157,  157,  158,  158,  158,  158,   93,   93,
      268,  268,  160,  161,  161,  161,  162,  162,  162,  162,
      268,  160,  162,  162,  162,  162,  163,  163,  163,  163,

       93,   93,  268,  268,  165,  166,  166,  166,  167,  167,
      167,  167,  268,  165,  167,  167,  167,  167,  168,  168,
      168,  168,   93,   93,  268,  268,  170,  171,  171,  171,
      172,  172,  172,  172,  268,  170,  172,  172,  172,  172,
      173,  173,  173,  173,   93,   93,  268,  268,  175,  176,
      176,  176,  177,  177,  177,  177,  268,  175,  177,  177,
      177,  177,  178,  178,  178,  178,   93,   93,  268,  268,
      180,  181,  181,  181,  182,  182,  182,  182,  268,  180,
      182,  182,  182,  182,  183,  183,  183,  183,   93,   93,
      268,  268,  185,  186,  186,  186,  187,  187,  187,  187,

      268,  185,  187,  187,  187,  187,  188,  188,  188,  188,
       93,   93,  268,  268,  190,  191,  191,  191,  192,  192,
      192,  192,  268,  190,  192,  192,  192,  192,  193,  193,
      193,  193,   93,   93,  268,  268,  195,  196,  196,  196,
      197,  197,  197,  197,  268,  195,  197,  197,  197,  197,
      198,  198,  198,  198,   93,   93,  268,  268,  200,  201,
      201,  201,  202,  202,  202,  202,  268,  200,  202,  202,
      202,  202,  203,  203,  203,  203,   93,   93,  268,  268,
      205,  206,  206,  206,  207,  207,  207,  207,  268,  205,
      207,  207,  207,  207,  208,  208,  208,  208,   93,   93,

      268,  268,  210,  211,  211,  211,  212,  212,  212,  212,
      268,  210,  212,  212,  212,  212,  213,  213,  213,  213,
       93,   93,  268,  268,  215,  216,  216,  216,  217,  217,
      217,  217,  268,  215,  217,  217,  217,  217,  218,  218,
      218,  218,   93,   93,  268,  268,  220,  221,  221,  221,
      222,  222,  222,  222,  268,  220,  222,  222,  222,  222,
      223,  223,  223,  223,   93,   93,  268,  268,  225,  226,
      226,  226,  227,  227,  227,  227,  268,  225,  227,  227,
      227,  227,  228,  228,  228,  228,   93,   93,  268,  268,
      230,  231,  231,  231,  232,  232,  232,  232,  268,  230,

      232,  232,  232,  232,  233,  233,  233,  233,   93,   93,
      268,  268,  235,  236,  236,  236,  237,  237,  237,  237,
      268,  235,  237,  237,  237,  237,  238,  238,  238,  238,
       93,   93,  268,  268,  240,  241,  241,  241,  242,  242,
      242,  242,  268,  240,  242,  242,  242,  242,  243,  243,
      243,  243,   93,   93,  268,  268,  245,  246,  246,  246,
      247,  247,  247,  247,  268,  245,  247,  247,  247,  247,
      248,  248,  248,  248,   93,   93,  268,  268,  250,  251,
      251,  251,  252,  252,  252,  252,  268,  250,  252,  252,
      252,  252,  253,  253,  253,  253,   93,   93,  268,  268,

      255,  256,  256,  256,  257,  257,  257,  257,  268,  255,
      257,  257,  257,  257,  258,  258,  258,  258,   93,   93,
      268,  268,  260,  261,  261,  261,  262,  262,  262,  262,
      268,  260,  262,  262,  262,  262,  263,  263,  263,  263,
       93,   93,  268,  268,  265,  266,  266,  266,  267,  267,
      267,  267,  268,  265,  267,  267,  267,  267,   31,   31,
       31,   31,   93,   93,  268,  268,   67,   94,   94,   94,
      114,  114,  114,  114,  268,   67,  114,  114,  114,  114,
       33,   33,   33,   33,   33,   38,   38,   40,   40,   40,
       40,   40,   44,  268,   44,   44,   44,   57,   57,   70,

       70,   73,   73,   73,   73,   73,   75,  268,   75,   75,
       75,   83,   83,   85,   85,  107,  107,  121,  121,  131,
      131,  138,  138,  144,  144,  149,  149,  154,  154,  159,
      159,  164,  164,  169,  169,  174,  174,  179,  179,  184,
      184,  189,  189,  194,  194,  199,  199,  204,  204,  209,
      209,  214,  214,  219,  219,  224,  224,  229,  229,  234,
      234,  239,  239,  244,  244,  249,  249,  254,  254,  259,
      259,  264,  264,    3,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268
    } ;

static yyconst short int yy_chk[1221] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        5,    5,    5,    5,    7,    7,    7,    7,    8,    7,
        9,    9,    9,    9,   10,   10,   10,   10,   12,    8,
        8,    8,    8,   11,  279,   12,   12,   12,   12,    8,
        9,   11,   11,   11,   11,   12,   13,   13,   13,   13,
       14,   14,   14,   14,   15,   15,   15,   15,   16,   24,

      136,   24,   16,   16,   16,   16,   16,   17,  128,   17,
       17,   17,   17,   18,  126,   18,   18,   18,   18,   22,
       22,   22,   22,   17,   19,   19,   19,   19,   19,   19,
      125,   28,   17,   28,   20,   20,   20,   20,   17,   20,
       21,   21,   21,   21,  116,   21,   21,   23,   23,   23,
       23,   25,   26,   25,   27,   27,   26,   33,   27,   40,
      113,   25,   30,   30,   30,   30,   23,   31,   31,   31,
       31,   44,   44,   44,   44,   31,   40,  112,   33,   49,
       49,   49,   49,  111,   31,  101,   50,   50,   50,   50,
       77,   77,   30,   35,   50,   51,   97,   51,   51,   51,

       51,  102,  102,   50,   35,   35,   35,   35,   79,   79,
       79,   92,   35,   52,   35,   52,   52,   52,   52,   91,
       74,   35,   42,   53,   74,   53,   53,   53,   53,   42,
       42,   42,   42,   90,   89,   67,   67,   42,   87,   42,
       67,   67,   67,   93,   93,   93,   42,   45,   83,   45,
       45,   45,   45,   73,   72,   72,   69,   45,   72,   72,
       72,   72,   94,   94,   94,   94,   45,   46,   66,   46,
       46,   46,   46,   56,   56,   56,   56,   46,   86,   86,
       65,   56,   64,   86,   86,   86,   46,  103,  103,  103,
       56,   68,   76,   76,   76,   76,   62,   61,   68,   68,

       76,   60,   59,   68,   68,   68,   95,   58,   55,   76,
       47,   43,   68,   71,   37,   36,   71,   71,   95,   95,
       95,   71,   71,   71,   32,   29,   96,   95,    3,    0,
       71,   78,    0,   78,   78,   78,   78,   96,   96,   96,
       96,   78,  109,  109,  109,  109,    0,   96,    0,   98,
       78,   80,    0,   80,   80,   80,   80,   98,   98,   98,
        0,   80,  105,  105,  105,    0,   98,  105,  105,  105,
       80,   82,    0,   82,   82,   82,   82,  108,  108,    0,
       82,   82,  108,  108,  108,    0,   82,   82,   82,   82,
       82,   82,   84,   84,   84,   84,   99,    0,    0,    0,

       84,    0,    0,   99,   99,   99,   99,    0,    0,   84,
        0,    0,    0,   99,  100,  100,  100,  100,  106,  106,
      106,  106,  100,    0,    0,  115,  106,  114,  114,  114,
      114,  100,    0,  117,    0,  106,  115,  115,  115,  115,
      117,  117,  117,  117,    0,    0,  115,    0,    0,    0,
      117,  118,  118,  118,  118,    0,    0,    0,  119,  118,
      119,  119,  119,  119,  120,  120,  120,  120,  118,  122,
      122,    0,  120,    0,  122,  122,  122,  123,  123,  123,
      123,  120,  124,  124,  124,  124,  130,  130,  130,  130,
      132,  132,    0,    0,  130,  132,  132,  132,  133,  133,

      133,  133,    0,  130,  134,  134,  134,  134,  137,  137,
      137,  137,  139,  139,    0,    0,  137,  139,  139,  139,
      140,  140,  140,  140,    0,  137,  141,  141,  141,  141,
      143,  143,  143,  143,  145,  145,    0,    0,  143,  145,
      145,  145,  146,  146,  146,  146,    0,  143,  147,  147,
      147,  147,  148,  148,  148,  148,  150,  150,    0,    0,
      148,  150,  150,  150,  151,  151,  151,  151,    0,  148,
      152,  152,  152,  152,  153,  153,  153,  153,  155,  155,
        0,    0,  153,  155,  155,  155,  156,  156,  156,  156,
        0,  153,  157,  157,  157,  157,  158,  158,  158,  158,

      160,  160,    0,    0,  158,  160,  160,  160,  161,  161,
      161,  161,    0,  158,  162,  162,  162,  162,  163,  163,
      163,  163,  165,  165,    0,    0,  163,  165,  165,  165,
      166,  166,  166,  166,    0,  163,  167,  167,  167,  167,
      168,  168,  168,  168,  170,  170,    0,    0,  168,  170,
      170,  170,  171,  171,  171,  171,    0,  168,  172,  172,
      172,  172,  173,  173,  173,  173,  175,  175,    0,    0,
      173,  175,  175,  175,  176,  176,  176,  176,    0,  173,
      177,  177,  177,  177,  178,  178,  178,  178,  180,  180,
        0,    0,  178,  180,  180,  180,  181,  181,  181,  181,

        0,  178,  182,  182,  182,  182,  183,  183,  183,  183,
      185,  185,    0,    0,  183,  185,  185,  185,  186,  186,
      186,  186,    0,  183,  187,  187,  187,  187,  188,  188,
      188,  188,  190,  190,    0,    0,  188,  190,  190,  190,
      191,  191,  191,  191,    0,  188,  192,  192,  192,  192,
      193,  193,  193,  193,  195,  195,    0,    0,  193,  195,
      195,  195,  196,  196,  196,  196,    0,  193,  197,  197,
      197,  197,  198,  198,  198,  198,  200,  200,    0,    0,
      198,  200,  200,  200,  201,  201,  201,  201,    0,  198,
      202,  202,  202,  202,  203,  203,  203,  203,  205,  205,

        0,    0,  203,  205,  205,  205,  206,  206,  206,  206,
        0,  203,  207,  207,  207,  207,  208,  208,  208,  208,
      210,  210,    0,    0,  208,  210,  210,  210,  211,  211,
      211,  211,    0,  208,  212,  212,  212,  212,  213,  213,
      213,  213,  215,  215,    0,    0,  213,  215,  215,  215,
      216,  216,  216,  216,    0,  213,  217,  217,  217,  217,
      218,  218,  218,  218,  220,  220,    0,    0,  218,  220,
      220,  220,  221,  221,  221,  221,    0,  218,  222,  222,
      222,  222,  223,  223,  223,  223,  225,  225,    0,    0,
      223,  225,  225,  225,  226,  226,  226,  226,    0,  223,

      227,  227,  227,  227,  228,  228,  228,  228,  230,  230,
        0,    0,  228,  230,  230,  230,  231,  231,  231,  231,
        0,  228,  232,  232,  232,  232,  233,  233,  233,  233,
      235,  235,    0,    0,  233,  235,  235,  235,  236,  236,
      236,  236,    0,  233,  237,  237,  237,  237,  238,  238,
      238,  238,  240,  240,    0,    0,  238,  240,  240,  240,
      241,  241,  241,  241,    0,  238,  242,  242,  242,  242,
      243,  243,  243,  243,  245,  245,    0,    0,  243,  245,
      245,  245,  246,  246,  246,  246,    0,  243,  247,  247,
      247,  247,  248,  248,  248,  248,  250,  250,    0,    0,

      248,  250,  250,  250,  251,  251,  251,  251,    0,  248,
      252,  252,  252,  252,  253,  253,  253,  253,  255,  255,
        0,    0,  253,  255,  255,  255,  256,  256,  256,  256,
        0,  253,  257,  257,  257,  257,  258,  258,  258,  258,
      260,  260,    0,    0,  258,  260,  260,  260,  261,  261,
      261,  261,    0,  258,  262,  262,  262,  262,  263,  263,
      263,  263,  265,  265,    0,    0,  263,  265,  265,  265,
      266,  266,  266,  266,    0,  263,  267,  267,  267,  267,
      269,  269,  269,  269,  269,  270,  270,  271,  271,  271,
      271,  271,  272,    0,  272,  272,  272,  273,  273,  274,

      274,  275,  275,  275,  275,  275,  276,    0,  276,  276,
      276,  277,  277,  278,  278,  280,  280,  281,  281,  282,
      282,  283,  283,  284,  284,  285,  285,  286,  286,  287,
      287,  288,  288,  289,  289,  290,  290,  291,  291,  292,
      292,  293,  293,  294,  294,  295,  295,  296,  296,  297,
      297,  298,  298,  299,  299,  300,  300,  301,  301,  302,
      302,  303,  303,  304,  304,  305,  305,  306,  306,  307,
      307,  308,  308,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "rules.l"
#define INITIAL 0
#line 2 "rules.l"
#include <stdio.h>
#line 729 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 5 "rules.l"


#line 883 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 269 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1174 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 7 "rules.l"
return 1;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 8 "rules.l"
return 2;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 9 "rules.l"
return 3;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 10 "rules.l"
return 4;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 11 "rules.l"
return 5;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 12 "rules.l"
return 6;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 13 "rules.l"
return 7;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 14 "rules.l"
return 8;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 15 "rules.l"
return 9;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 16 "rules.l"
return 10;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 17 "rules.l"
return 11;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 18 "rules.l"
return 12;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 19 "rules.l"
return 13;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 20 "rules.l"
return 14;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 21 "rules.l"
return 15;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 22 "rules.l"
return 16;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 23 "rules.l"
return 17;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 24 "rules.l"
return 18;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 26 "rules.l"
ECHO;
	YY_BREAK
#line 1061 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 269 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 269 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 268);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 26 "rules.l"


int num_tokens = 18;

int yywrap(void){
return 1;
}